connection: "localhost"
userprofile: "hui"
account: "pizda"
game: "afk"
taskconfigs:
    - cfg/reactions.yaml
    - cfg/daily.yaml
dirs:
    root: .afkworker
    sqDB: db
    testData: _test
    gameConf: cfg
    tempImg: work_images
    user: usrdata
required_installed_software:
    - adb
    - magick
    - tesseract
    - HD-Player
