// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentConfiguration() {
  return window['go']['backend']['Config']['CurrentConfiguration']();
}

export function CurrentPilot() {
  return window['go']['backend']['Config']['CurrentPilot']();
}

export function Load(arg1, arg2) {
  return window['go']['backend']['Config']['Load'](arg1, arg2);
}

export function Store(arg1, arg2, arg3) {
  return window['go']['backend']['Config']['Store'](arg1, arg2, arg3);
}

export function WailsInit() {
  return window['go']['backend']['Config']['WailsInit']();
}
