// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdbConnect(arg1) {
  return window['go']['backend']['Config']['AdbConnect'](arg1);
}

export function WailsInit(arg1) {
  return window['go']['backend']['Config']['WailsInit'](arg1);
}
