// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function CurrentConfiguration():Promise<settings.Settings>;

export function CurrentPilot():Promise<settings.Pilot>;

export function Load(arg1:string,arg2:boolean):Promise<Array<number>>;

export function Store(arg1:Array<number>,arg2:string,arg3:boolean):Promise<void>;

export function WailsInit():Promise<void>;
