#######################################################################
################## FIGHT RELATED LOCATIONS ############################
#######################################################################
battlescreen:
    name: battlescreen
    hits: 1
    keywords:
        - Forntions
        - formations
        - Formations
        - Stage
        - VS)
    actions:
        Fight:
            point:
                x: "530"
                "y": "2450"
            properties:
                check: false
                delay: 1
                repeat: 0
        Formations:
            point:
                x: "950"
                "y": "2450"
            properties:
                check: false
                delay: 1
                repeat: 0
campvictory:
    name: victory
    hits: 1
    keywords:
       - next
       - Fall
       - Rewards 
       - Next 
       - Stage 
       - in> 
    actions:
        battlestat:
            point:
                x: "1000"
                "y": "2360"
            properties:
                check: false
                delay: 1
        next: 
            point:
                x: "500"
                "y": "2360"
            properties:
                check: false
                delay: 1
losecampain:
    hits: 2
    name: battleresult
    keywords:
        - Continue
        - Raise
        - increase
        - strength
        - Tier
        - using
        - methods
        - below.
        - Level
    actions:
        Retry:
            point:
                x: "530"
                "y": "2350"
            properties:
                check: false
                delay: 1
                repeat: 0
        battlestat:
            point:
                x: "980"
                "y": "2360"
            properties:
                check: false
                delay: 1
                repeat: 0

battlestat:
    hits: 1
    name: stat
    keywords:
       - Statistics
    actions:
        back:
            point:
                x: "999"
                "y": "350"
            properties:
                check: false
                delay: 1
        heroinfo:
            point:
                x: "370"
                "y": "2050"
            properties:
                check: false
                delay: 1

#######################################################################
################## MAIN SCREEN LOCATIONS ##############################
#######################################################################
################## Global locations ###################################
#######################################################################

campain:
    name: campain
    hits: 2
    keywords:
        - Fast 
        - Rewards
        - World 
        - Map
        - Tales
    actions:
        BeginCampain:
            point:
                x: "530"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0
        BeginBoss:
            point:
                x: "530"
                "y": "1800"
            properties:
                check: false
                delay: 1
                repeat: 0
        afkchest:
            point:
                x: "560"
                "y": "2100"
            properties:
                check: false
                delay: 1
                repeat: 0
        darkforest:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        fastrewards:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0
        heroes:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        leftbanner:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        ranhorn:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        rightbanner:
            point:
                x: "970"
                "y": "430"
            properties:
                check: false
                delay: 1
                repeat: 0
        back:
            point:
                x: "10"
                "y": "2500"
            properties:
                check: false
                delay: 1
                repeat: 0
        usefr:
            point:
                x: "600"
                "y": "1580"
            properties:
                check: false
                delay: 1
                repeat: 0
        darkforrest:
            point:
                x: "320"
                "y": "2450"
            properties:
                check: false
                delay: 1
                repeat: 0
forrest:
    name: forrest
    hits: 1
    keywords:
        - Arena 
        - labyrnts
    actions:
        back:
            point:
                x: "10"
                "y": "2500"
            properties:
                check: false
                delay: 1
                repeat: 0
        darkforest:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0

        heroes:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        leftbanner:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0

        ranhorn:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        rightbanner:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        kingstower:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        arena:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
ranhorn:
    name: ranhorn
    hits: 3
    keywords:
        - Guild
        - Shop
        - Library
        - Resonating
        - Crystal
        - Beast
        - Grounds
        - Rickety
        - Cart
        - Noble
        - Tavern
    actions:
        shop:
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        guild:
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        oak: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1

#######################################################################
##################### BANNERS CHILD LOCATIONS #########################
#######################################################################
# Not work rn, manipulation with dynamic content hard to develop
# TODO: collect dailies
leftbanner:
    name: leftbanner
    hits: 2
    keywords:
        # - Merchants
        # - Purchase Gift
        # - Events
    actions:
        merch: 
            point:
                x: 100
                "y": 300
            properties:
                check: false
                delay: 1
        events: 
            point:
                x: 100
                "y": 500
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0
        close:
            point:
                x: 960
                "y": 1350
rightbanner:
    name: rightbanner
    hits: 3
    keywords:
        - Bag
        - Mail
        - Friends
        - Solemn
        - Vow
        - Community
    actions:
        quest: 
            point:
                x: 950
                "y": 300
            properties:
                check: false
                delay: 1
        bag: 
            point:
                x: 950
                "y": 500
            properties:
                check: false
                delay: 1
        mail: 
            point:
                x: 950
                "y": 700
            properties:
                check: false
                delay: 1
        friends: 
            point:
                x: 950
                "y": 900
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                repeat: 0
        close:
            point:
                x: 960
                "y": 1350
        
friends:
    name: friends
    keywords:
        - Friends
        - Garrisoned
    actions:
        sendrecive:
            point:
                x: 900
                "y": 2250
        back:
            point:
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                repeat: 0
mail:
    name: mail
    keywords:
        - collect
        - all
        - delete
    actions:
        mailcollect:
            point:
                x: 800
                "y": 2100
            properties:
                delay: 1
        back:
            point:
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                    
#######################################################################
##################### CAMPAIN CHILD LOCATIONS #########################
#######################################################################

campainBoss:
    name: campainBoss
    hits: 2
    keywords:
        - Enemny
        - Formation
        - Completition
        - Rewards
        - ormavion
    actions:
        BeginBoss:
            point:
                x: "530"
                "y": "1800"
            properties:
                check: false
                delay: 1
                repeat: 0
        back:
            point:
                x: "50"
                "y": "2480"
                # x: "930"
                # "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0
fastrewards:
    name: fastrewards
    hits: 0
    keywords: []
    actions:
        back:
            point:
                # x: "930"
                # "y": "2300"
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                repeat: 0
        usefr:
            point:
                x: "600"
                "y": "1580"
            properties:
                check: false
                delay: 1
                repeat: 0
afkchest:
    hits: 2
    name: afkchest
    keywords:
        - Tap
        - the
        - blank
        - area 
        - to\nclaim 
        - AFK
        - Rewards
    actions:
        back:
            point:
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                repeat: 0

#######################################################################
##################### DARK FOREST CHILD LOCATIONS #####################
#######################################################################

arena: 
    name: arena
    hits: 2
    keywords:
        - season
        - challeger
        - tournament
        - championship
        - starts
        - gladiator
    actions:
        oneonone: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        3team: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                repeat: 0
kingstower:
    name: kt
    hits: 2
    keywords:
        - forsaken
        - necropolis
        - World
        - tree
        - infernal
        - fortress
        - sanctum
        - tower
        - light
        - 
    actions:
        kt: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        cele: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                repeat: 0

#######################################################################
####################### RANHORNY TAB CHILD LOCATIONS ##################
#######################################################################

guild:
    name: guildgrounds
    hits: 2
    keywords:
        - Guild
        - Hall
        - Hellscape
        - Grounds
        - Hunting
    actions:
        bosses: 
            point:
                x: 300
                "y": 900
            properties:
                check: false
                delay: 1
        hell: 
            point:
                x: 300
                "y": 750
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                repeat: 0
wrizz:
    name: wrizz
    hits: 1
    keywords:
        - wrizz
        - Challenge
    actions:
        Fight:

shop:
    name: shop
    hits: 2
    keywords:
        - goods
        - barracks
    actions:
        buydust: 
            point:
                x: 
                "y":
            properties:
                check: false
                delay: 1
        buypoegold: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        buypoedia: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        buycoresy: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        reset: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                repeat: 0
bosses:
    name: bosses
    hits: 1
    keywords:
        - wrizz
    actions:
        challenge: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        quikfigt: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "50"
                "y": "2480"
            properties:
                check: false
                delay: 1
                repeat: 0

# <location>:
#     name:
#     hits:
#     keywords:
#         - #word1
#         - #word2
#     actions:
#         <act1>: 
#             point:
#                 x:
#                 "y":
#             properties:
#                 check: false
#                 delay: 1
#         <act2>: 
#             point:
#                 x:
#                 "y":
#             properties:
#                 check: false
#                 delay: 1
        # back:
        #     point:
        #         x: "930"
        #         "y": "2300"
        #     properties:
        #         check: false
        #         delay: 1
        #         repeat: 0