battlescreen:
    name: battlescreen
    hits: 1
    keywords:
        - Forntions
        - formations
        - Formations
        - Stage
        - VS)
    actions:
        Fight:
            point:
                x: "530"
                "y": "2450"
            properties:
                check: false
                delay: 1
                repeat: 0
        Formations:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
losecampain:
    hits: 2
    name: battleresult
    keywords:
        - Continue
        - Raise
        - increase
        - strength
        - Tier
        - using
        - methods
        - below.
        - Level
    actions:
        Next:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        Retry:
            point:
                x: "530"
                "y": "2350"
            properties:
                check: false
                delay: 1
                repeat: 0
        Stat:
            point:
                x: "980"
                "y": "2360"
            properties:
                check: false
                delay: 1
                repeat: 0
afkchest:
    hits: 2
    name: afkchest
    keywords:
        - Tap
        - the
        - blank
        - area 
        - to\nclaim 
        - AFK
        - Rewards
    actions:
        back:
            point:
                x: "10"
                "y": "2500"
            properties:
                check: false
                delay: 1
                repeat: 0
campain:
    name: campain
    hits: 2
    keywords:
        - Fast 
        - Rewards
        - World 
        - Map
        - Tales
    actions:
        BeginCampain:
            point:
                x: "530"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0
        BeginBoss:
            point:
                x: "530"
                "y": "1800"
            properties:
                check: false
                delay: 1
                repeat: 0
        afkchest:
            point:
                x: "560"
                "y": "2100"
            properties:
                check: false
                delay: 1
                repeat: 0
        darkforest:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        fastreward:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0
        heroes:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        leftbanner:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        ranhorn:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        rightbanner:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        back:
            point:
                x: "10"
                "y": "2500"
            properties:
                check: false
                delay: 1
                repeat: 0
        usefr:
            point:
                x: "600"
                "y": "1580"
            properties:
                check: false
                delay: 1
                repeat: 0
        darkforrest:
            point:
                x: "320"
                "y": "2450"
            properties:
                check: false
                delay: 1
                repeat: 0
campainBoss:
    name: campainBoss
    hits: 2
    keywords:
        - Enemny
        - Formation
        - Completition
        - Rewards
        - ormavion
    actions:
        BeginBoss:
            point:
                x: "530"
                "y": "1800"
            properties:
                check: false
                delay: 1
                repeat: 0
        back:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0
fastrewards:
    name: fastrewards
    hits: 0
    keywords: []
    actions:
        back:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0
        usefr:
            point:
                x: "600"
                "y": "1580"
            properties:
                check: false
                delay: 1
                repeat: 0

forrest:
    name: forrest
    hits: 1
    keywords:
        - Arena 
        - labyrnts
    actions:
        back:
            point:
                x: "10"
                "y": "2500"
            properties:
                check: false
                delay: 1
                repeat: 0
        darkforest:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0

        heroes:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        leftbanner:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0

        ranhorn:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        rightbanner:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        kingstower:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0
        arena:
            point:
                x: ""
                "y": ""
            properties:
                check: false
                delay: 1
                repeat: 0

kingstower:
    name: kt
    hits: 2
    keywords:
        - forsaken
        - necropolis
        - World
        - tree
        - infernal
        - fortress
        - sanctum
        - tower
        - light
        - 
    actions:
        kt: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        cele: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0


                
arena: 
    name: arena
    hits: 2
    keywords:
        - season
        - challeger
        - tournament
        - championship
        - starts
        - gladiator
    actions:
        oneonone: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        3team: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0

campvictory:
    name: victory
    hits: 1
    keywords:
       - next
       - Fall
       - Rewards 
       - Next 
       - Stage 
       - in> 
       - Tap 
       - Continue
    actions:
        battlestat:
            point:
                x: "1000"
                "y": "2360"
            properties:
                check: false
                delay: 1
        next: 
            point:
                x: "500"
                "y": "2360"
            properties:
                check: false
                delay: 1
        heroinfo:
            point:
                x: "1000"
                "y": "2360"
            properties:
                check: false
                delay: 1
stat:
    hits: 1
    name: stat
    keywords:
       - Statistics
    actions:
        back:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
ranhorn:
    name: ranhorn
    hits: 3
    keywords:
        - Guild
        - Shop
        - Library
        - Resonating
        - Crystal
        - Beast
        - Grounds
        - Rickety
        - Cart
        - Noble
        - Tavern
    actions:
        shop:
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        guild:
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        oak: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1

guild:
    name:
    hits:
    keywords:
        - #word1
        - #word2
    actions:
        bosses: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        hell: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0

shop:
    name: shop
    hits: 2
    keywords:
        - goods
        - barracks
    actions:
        buydust: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        buypoegold: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        buypoedia: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        buycoresy: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        reset: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0


bosses:
    name: bosses
    hits: 1
    keywords:
        - wrizz
    actions:
        challenge: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        quikfigt: 
            point:
                x:
                "y":
            properties:
                check: false
                delay: 1
        back:
            point:
                x: "930"
                "y": "2300"
            properties:
                check: false
                delay: 1
                repeat: 0

# <location>:
#     name:
#     hits:
#     keywords:
#         - #word1
#         - #word2
#     actions:
#         <act1>: 
#             point:
#                 x:
#                 "y":
#             properties:
#                 check: false
#                 delay: 1
#         <act2>: 
#             point:
#                 x:
#                 "y":
#             properties:
#                 check: false
#                 delay: 1
        # back:
        #     point:
        #         x: "930"
        #         "y": "2300"
        #     properties:
        #         check: false
        #         delay: 1
        #         repeat: 0