// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AdbConnect(arg1:string):Promise<boolean|string>;

export function Greet(arg1:string):Promise<string>;

export function Search(arg1:string,arg2:string,arg3:main.OptionsType):Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;
